import { useCallback, useEffect, useRef } from "react";
import {
    BackHandler,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
    useWindowDimensions,
} from "react-native";
import BottomSheet, {
    BottomSheetBackdrop,
    BottomSheetScrollView,
} from "@gorhom/bottom-sheet";
import { Portal } from "@gorhom/portal";
import AppIcon, { AppIconName } from "./AppIcon";
import { borderRadius, colors, scaleFontSize, shadows } from "../lib/theme";
import { FONT_DISPLAY } from "../lib/fonts";

const ANIMATION_DURATION = 250;

// The disclosure itself. Kept here so the consent copy lives in one place and
// the Settings row can point at the same sheet.
const DISCLOSURE: { icon: AppIconName; title: string; body: string }[] = [
    {
        icon: "mic",
        title: "What gets recorded",
        body: "Only what you say while the recorder is open. Nothing is captured in the background.",
    },
    {
        icon: "zap",
        title: "Where it goes",
        body: "Your recording is uploaded to our backend and passed to secure AI services that turn speech into text, then work out what the reminder is and when it's due.",
    },
    {
        icon: "volume-2",
        title: "The voice you hear back",
        body: "Your reminder is spoken by a synthetic voice, generated by our AI partners.",
    },
];

export type AiConsentSheetProps = {
    visible: boolean;
    onAgree: () => void;
    /** Called on "Not now", backdrop tap, swipe-down and Android back. */
    onDecline: () => void;
    hostName?: string;
};

export default function AiConsentSheet({
    visible,
    onAgree,
    onDecline,
    hostName = "root",
}: AiConsentSheetProps) {
    const bottomSheetRef = useRef<BottomSheet>(null);
    const { height: windowHeight } = useWindowDimensions();

    // Handle visibility changes
    useEffect(() => {
        if (visible) {
            bottomSheetRef.current?.snapToIndex(0);
        } else {
            bottomSheetRef.current?.close();
        }
    }, [visible]);

    // Handle Android back button — backing out is a decline, not an agree.
    useEffect(() => {
        if (!visible) return;

        const backHandler = BackHandler.addEventListener("hardwareBackPress", () => {
            onDecline();
            return true;
        });

        return () => backHandler.remove();
    }, [visible, onDecline]);

    const renderBackdrop = useCallback(
        (props: any) => (
            <BottomSheetBackdrop
                {...props}
                disappearsOnIndex={-1}
                appearsOnIndex={0}
                opacity={0.25}
                pressBehavior="close"
            />
        ),
        []
    );

    const handleSheetChange = useCallback(
        (index: number) => {
            if (index === -1) {
                onDecline();
            }
        },
        [onDecline]
    );

    const handleAgree = useCallback(() => {
        onAgree();
        bottomSheetRef.current?.close();
    }, [onAgree]);

    if (!visible) return null;

    return (
        <Portal hostName={hostName}>
            <BottomSheet
                ref={bottomSheetRef}
                index={0}
                enablePanDownToClose
                enableDynamicSizing
                maxDynamicContentSize={Math.round(windowHeight * 0.9)}
                animationConfigs={{ duration: ANIMATION_DURATION }}
                backdropComponent={renderBackdrop}
                onChange={handleSheetChange}
                handleIndicatorStyle={styles.handleIndicator}
                backgroundStyle={styles.sheetBackground}
            >
                <BottomSheetScrollView
                    contentContainerStyle={styles.content}
                    showsVerticalScrollIndicator={false}
                >
                    <Text style={styles.title}>Your voice leaves your phone</Text>
                    <Text style={styles.subtitle}>
                        To turn what you say into a reminder, Voice Reminder sends your recording to
                        secure AI services run by our partners. Here's exactly what happens.
                    </Text>

                    <View style={styles.card}>
                        {DISCLOSURE.map((item, index) => (
                            <View key={item.title}>
                                {index > 0 ? <View style={styles.separator} /> : null}
                                <View style={styles.row}>
                                    <View style={styles.rowIcon}>
                                        <AppIcon
                                            name={item.icon}
                                            size={20}
                                            color={colors.textSecondary}
                                        />
                                    </View>
                                    <View style={styles.rowTextWrap}>
                                        <Text style={styles.rowTitle}>{item.title}</Text>
                                        <Text style={styles.rowBody}>{item.body}</Text>
                                    </View>
                                </View>
                            </View>
                        ))}
                    </View>

                    <Text style={styles.footnote}>
                        These companies process your recording so the app can work — we don't sell it
                        or use it for advertising. You can withdraw consent any time in Settings.
                        Choose "Not now" and nothing is recorded.
                    </Text>

                    <View style={styles.actions}>
                        <TouchableOpacity
                            style={styles.declineButton}
                            onPress={onDecline}
                            activeOpacity={0.7}
                        >
                            <Text style={styles.declineText}>Not now</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                            style={styles.agreeButton}
                            onPress={handleAgree}
                            activeOpacity={0.7}
                        >
                            <Text style={styles.agreeText}>Agree & record</Text>
                        </TouchableOpacity>
                    </View>
                </BottomSheetScrollView>
            </BottomSheet>
        </Portal>
    );
}

const styles = StyleSheet.create({
    handleIndicator: {
        backgroundColor: "#e0e0e0",
        width: 36,
    },
    sheetBackground: {
        backgroundColor: colors.background,
        borderTopLeftRadius: borderRadius.sheet,
        borderTopRightRadius: borderRadius.sheet,
    },
    content: {
        paddingHorizontal: 20,
        paddingBottom: 32,
    },
    title: {
        fontFamily: FONT_DISPLAY,
        fontSize: scaleFontSize(24),
        color: colors.textHeading,
        marginTop: 10,
        marginBottom: 8,
    },
    subtitle: {
        fontSize: scaleFontSize(14),
        lineHeight: scaleFontSize(20),
        color: colors.textSecondary,
    },

    // Disclosure card
    card: {
        backgroundColor: colors.card,
        borderRadius: borderRadius.lg,
        marginTop: 16,
        paddingHorizontal: 16,
        ...shadows.card,
    },
    separator: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: colors.border,
        marginLeft: 48,
    },
    row: {
        flexDirection: "row",
        alignItems: "flex-start",
        paddingVertical: 14,
    },
    rowIcon: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: colors.surface,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    rowTextWrap: {
        flex: 1,
    },
    rowTitle: {
        fontSize: scaleFontSize(15),
        fontWeight: "600",
        color: colors.textPrimary,
    },
    rowBody: {
        fontSize: scaleFontSize(13),
        lineHeight: scaleFontSize(19),
        color: colors.textSecondary,
        marginTop: 2,
    },

    footnote: {
        fontSize: scaleFontSize(12),
        lineHeight: scaleFontSize(17),
        color: colors.textTertiary,
        marginTop: 14,
    },

    actions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 20,
        gap: 12,
    },
    declineButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: borderRadius.md,
        backgroundColor: colors.surfaceAlt,
        alignItems: "center",
    },
    declineText: {
        fontSize: scaleFontSize(15),
        fontWeight: "600",
        color: colors.textSecondary,
    },
    agreeButton: {
        flex: 1.3,
        paddingVertical: 14,
        borderRadius: borderRadius.md,
        backgroundColor: colors.accent,
        alignItems: "center",
    },
    agreeText: {
        fontSize: scaleFontSize(15),
        fontWeight: "600",
        color: "#ffffff",
    },
});
