name: Publish iOS update to production

jobs:
  publish_ios_production_update:
    type: update
    environment: production
    params:
      branch: production
      platform: ios
      message: "main @ 81cbaa5 (messages from Remi; instant swipe-to-discard)"
