name: Publish iOS update to production

jobs:
  publish_ios_production_update:
    type: update
    environment: production
    params:
      branch: production
      platform: ios
      message: "main @ 4ed05c0 (instant swipe-to-discard on failed and asking cards)"
