name: Publish iOS update to production

jobs:
  publish_ios_production_update:
    type: update
    environment: production
    params:
      branch: production
      platform: ios
      message: "main @ 2d1791a (remember each device's spoken language; correct language tagging)"
